#ifndef __UART_ASYNC_H__
#define __UART_ASYNC_H__

enum uart_async_status {
	UART_ASYNC_TX_IDLE = 0,
	UART_ASYNC_TX_BUSY,
	UART_ASYNC_STATE_FRAME_ERROR,
	UART_ASYNC_STATE_OVERRUN_ERROR,
	UART_ASYNC_STATE_PARITY_ERROR,
	UART_ASYNC_STATE_BUFFER_OVERFLOW,
};

#endif // __UART_ASYNC_H__